# Site settings
author: Jay
title: Wall Spaghetti Code
header-img: img/home-bg.png
email: januarydwilson@gmail.com
copyright_name: Jay
description: > # this means to ignore newlines until "baseurl:"
  A head soup of different ideas
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  EnerioJJ

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
